services:
  stock-web:
    image: stock-web:latest
    container_name: stock-web
    user: "0:0"
    environment:
      PORT: "8080"
      STOCKCALC_DATA_DIR: /data
    ports:
      - "8088:8080"
    volumes:
      - ./data:/data
    restart: always
